version: "3.9"

services:
  transactionpostgrescompany:
    image: postgres
    container_name: transactionpostgrescompany
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks: 
      - network-main-company

  transactionpgadmincompany:
    image: dpage/pgadmin4
    user: root
    container_name: transactionpgadmincompany
    environment:
      PGADMIN_DEFAULT_EMAIL: "otavio@otavio.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "8080:80"
    links:
      - transactionpostgrescompany
    depends_on:
      - transactionpostgrescompany
    networks:
      - network-main-company

networks:
  network-main-company:
    driver: bridge